<form method="POST" action="../../index.php" id="registerForm">
    <fieldset>
        <label for="firstName">First Name</label>
        <input type="text" name="firstName" id="firstName" required/>
    </fieldset>
    <fieldset>
        <label for="lastName">Last Name</label>
        <input type="text" name="lastName" id="lastName" required/>
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required/>
    </fieldset>
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required/>
    </fieldset>
    <fieldset>
        <label for="confirmPassword">Confirm Password</label>
        <input type="password" name="confirmPassword" id="confirmPassword" required/>
    </fieldset>
    <fieldset>
        <input type="submit" name="submit" id="submit" value="Créer un compte"/>
    </fieldset>
        <input type="hidden" name="formName" id="formName" value="registerForm"/>
</form>